fix: replace video mds for Feb. update script to check for every thumbprint for video

diff --git a/replacevmds b/replacevmds
--- a/replacevmds
+++ b/replacevmds
@@ -24,15 +24,28 @@ vidmd() {
   if imgurl="$(thumbnailurl "$vidid")"; then
     printf "[![%s](%s)](%s \"%s\")\n" "$caption" "$imgurl" "$vidurl" "$caption"
   else
-    echo >&2 "Thumbnail $imgurl not verifiable or invalid"
+    echo >&2 "Thumbnails unverifiable,invalid or absent."
     return 1
   fi
 }
 
 thumbnailurl() {
-  url="https://img.youtube.com/vi/${1}/maxresdefault.jpg"
-  echo "$url"
-  test 200 -eq "$(curl -o /dev/null --silent -Iw '%{http_code}' "${url}")"
+  urls=("https://img.youtube.com/vi/${1}/maxresdefault.jpg"
+    "https://img.youtube.com/vi/${1}/hqdefault.jpg"
+    "https://img.youtube.com/vi/${1}/mqdefault.jpg"
+    "https://img.youtube.com/vi/${1}/sddefault.jpg"
+    "https://img.youtube.com/vi/${1}/default.jpg"
+    "https://img.youtube.com/vi/${1}/0.jpg"
+    "https://img.youtube.com/vi/${1}/1.jpg"
+    "https://img.youtube.com/vi/${1}/2.jpg"
+    "https://img.youtube.com/vi/${1}/3.jpg")
+  for url in "${urls[@]}"; do
+    if test 200 -eq "$(curl -o /dev/null --silent -Iw '%{http_code}' "${url}")"; then
+      echo "$url"
+      return 0
+    fi
+  done
+  return 1
 }
 
 require() {
@@ -62,7 +75,7 @@ if isvalid "$dir"; then
     cd "$dir" || exit
     shopt -s nullglob
     for fname in ./*.md; do
-      echo "$fname"
+      echo "Processing ${fname} ..."
       tmp="$(mktemp)"
       declare -i count=0
       _matched=true
